global:
  scrape_interval: 15s

#rule_files:
#  - "alert.rules.yml"

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]

#  - job_name: 'remote-ubuntu-node'
#    static_configs:
#      - targets: [ 'remote-ubuntu:9100' ]

  - job_name: 'event-producer'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'event-producer:8090' ]

  - job_name: 'event-consumer'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'event-consumer:8091' ]

  - job_name: 'event-public-api'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'event-public-api:8092' ]

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: [ 'kafka-exporter:9308' ]